list(APPEND _vire_Vire_MOS_RESOURCES_FILES
${PROJECT_SOURCE_DIR}/plugins/Vire_MOS/resources/data/mos/xml/README.rst
${PROJECT_SOURCE_DIR}/plugins/Vire_MOS/resources/data/mos/xml/2.0.3/MOS_Structure.xsd
${PROJECT_SOURCE_DIR}/plugins/Vire_MOS/resources/data/mos/xml/2.0.3/MOS_SimpleDefinition.xsd
${PROJECT_SOURCE_DIR}/plugins/Vire_MOS/resources/data/mos/xml/2.0.3/README.rst
${PROJECT_SOURCE_DIR}/plugins/Vire_MOS/resources/data/mos/xml/2.0.3/MOS_Alarm.xsd
${PROJECT_SOURCE_DIR}/plugins/Vire_MOS/resources/data/mos/xml/2.0.3/MOS_FSM.xsd
${PROJECT_SOURCE_DIR}/plugins/Vire_MOS/resources/data/mos/xml/2.0.3/MOS_HardwareInterface.xsd
${PROJECT_SOURCE_DIR}/plugins/Vire_MOS/resources/data/mos/xml/2.0.3/MOS_Unit.xsd
${PROJECT_SOURCE_DIR}/plugins/Vire_MOS/resources/data/mos/xml/2.0.3/MOS_OPCUA.xsd
${PROJECT_SOURCE_DIR}/plugins/Vire_MOS/resources/data/mos/xml/2.0.4/MOS_Structure.xsd
${PROJECT_SOURCE_DIR}/plugins/Vire_MOS/resources/data/mos/xml/2.0.4/MOS_SimpleDefinition.xsd
${PROJECT_SOURCE_DIR}/plugins/Vire_MOS/resources/data/mos/xml/2.0.4/README.rst
${PROJECT_SOURCE_DIR}/plugins/Vire_MOS/resources/data/mos/xml/2.0.4/MOS_Alarm.xsd
${PROJECT_SOURCE_DIR}/plugins/Vire_MOS/resources/data/mos/xml/2.0.4/MOS_FSM.xsd
${PROJECT_SOURCE_DIR}/plugins/Vire_MOS/resources/data/mos/xml/2.0.4/MOS_HardwareInterface.xsd
${PROJECT_SOURCE_DIR}/plugins/Vire_MOS/resources/data/mos/xml/2.0.4/MOS_Unit.xsd
${PROJECT_SOURCE_DIR}/plugins/Vire_MOS/resources/data/mos/xml/2.0.4/MOS_OPCUA.xsd
${PROJECT_SOURCE_DIR}/plugins/Vire_MOS/resources/data/mos/xml/2.0.0/MOS_Structure.xsd
${PROJECT_SOURCE_DIR}/plugins/Vire_MOS/resources/data/mos/xml/2.0.0/MOS_SimpleDefinition.xsd
${PROJECT_SOURCE_DIR}/plugins/Vire_MOS/resources/data/mos/xml/2.0.0/MOS_Alarm.xsd
${PROJECT_SOURCE_DIR}/plugins/Vire_MOS/resources/data/mos/xml/2.0.0/MOS_FSM.xsd
${PROJECT_SOURCE_DIR}/plugins/Vire_MOS/resources/data/mos/xml/2.0.0/MOS_HardwareInterface.xsd
${PROJECT_SOURCE_DIR}/plugins/Vire_MOS/resources/data/mos/xml/2.0.0/MOS_Unit.xsd
${PROJECT_SOURCE_DIR}/plugins/Vire_MOS/resources/data/mos/xml/2.0.0/MOS_OPCUA.xsd
${PROJECT_SOURCE_DIR}/plugins/Vire_MOS/resources/data/mos/xml/2.0.1/MOS_Structure.xsd
${PROJECT_SOURCE_DIR}/plugins/Vire_MOS/resources/data/mos/xml/2.0.1/MOS_SimpleDefinition.xsd
${PROJECT_SOURCE_DIR}/plugins/Vire_MOS/resources/data/mos/xml/2.0.1/README.rst
${PROJECT_SOURCE_DIR}/plugins/Vire_MOS/resources/data/mos/xml/2.0.1/MOS_FSM.xsd
${PROJECT_SOURCE_DIR}/plugins/Vire_MOS/resources/data/mos/xml/2.0.1/MOS_HardwareInterface.xsd
${PROJECT_SOURCE_DIR}/plugins/Vire_MOS/resources/data/mos/xml/2.0.1/MOS_Unit.xsd
${PROJECT_SOURCE_DIR}/plugins/Vire_MOS/resources/data/mos/xml/2.0.1/MOS_OPCUA.xsd
${PROJECT_SOURCE_DIR}/plugins/Vire_MOS/resources/data/mos/xml/0.1/README.rst
${PROJECT_SOURCE_DIR}/plugins/Vire_MOS/resources/data/mos/xml/0.1/dict_mos.xsd
${PROJECT_SOURCE_DIR}/plugins/Vire_MOS/resources/data/mos/xml/0.1/unit.xsd
${PROJECT_SOURCE_DIR}/plugins/Vire_MOS/resources/data/mos/xml/2.0.2/MOS_Structure.xsd
${PROJECT_SOURCE_DIR}/plugins/Vire_MOS/resources/data/mos/xml/2.0.2/MOS_SimpleDefinition.xsd
${PROJECT_SOURCE_DIR}/plugins/Vire_MOS/resources/data/mos/xml/2.0.2/README.rst
${PROJECT_SOURCE_DIR}/plugins/Vire_MOS/resources/data/mos/xml/2.0.2/MOS_Alarm.xsd
${PROJECT_SOURCE_DIR}/plugins/Vire_MOS/resources/data/mos/xml/2.0.2/MOS_FSM.xsd
${PROJECT_SOURCE_DIR}/plugins/Vire_MOS/resources/data/mos/xml/2.0.2/MOS_HardwareInterface.xsd
${PROJECT_SOURCE_DIR}/plugins/Vire_MOS/resources/data/mos/xml/2.0.2/MOS_Unit.xsd
${PROJECT_SOURCE_DIR}/plugins/Vire_MOS/resources/data/mos/xml/2.0.2/MOS_OPCUA.xsd
)
