list(APPEND VireLibrary_HEADERS
  device/utils.h
  device/local_role.h
  device/space.h
  device/space-reflect.h
  device/slot_utils.h
  device/slot.h
  device/slot-reflect.h
  device/slot-serial.ipp
  device/i_instance.h
  device/i_instance-reflect.h
  device/single_instance.h
  device/single_instance-reflect.h
  device/regular_1d_instance.h
  # device/regular_1d_instance-reflect.h
  device/regular_2d_instance.h
  # device/regular_2d_instance-reflect.h
  device/multiple_instance.h
  # device/multiple_instance-reflect.h
  device/logical_link.h
  device/link_types.h
  device/link_types-reflect.h
  device/port_types.h
  device/port_types-reflect.h
  device/port_utils.h
  device/port_utils-reflect.h
  device/device_types.h
  device/device_types-reflect.h
  device/device_macros.h
  device/device_utils.h
  device/logical_device.h
  device/logical_port.h
  device/base_physical.h
  device/physical_device.h
  device/base_device_model.h
  device/base_port_model.h
  device/base_method_port_model.h
  device/base_link_model.h
  device/physical_port.h
  device/physical_link.h
  device/device_info.h
  device/mapping.h
  device/mapping_info.h
  device/mapping_utils.h
  device/manager.h
  device/manager-inl.h
  device/base_integrated_circuit_model.h
  device/base_electronics_module_model.h
  device/base_electronics_crate_model.h
  device/base_rackable_model.h
  device/base_electronics_rack_model.h
  device/base_firmware_model.h
  device/base_datapoint_model.h
  device/manager_command_interface.h
  device/link_end_info.h
  device/device_link_info.h
  )

list(APPEND VireLibrary_SOURCES
  device/utils.cc
  device/local_role.cc
  device/space.cc
  device/slot.cc
  device/i_instance.cc
  device/single_instance.cc
  device/regular_1d_instance.cc
  device/regular_2d_instance.cc
  device/multiple_instance.cc
  device/port_types.cc
  device/port_utils.cc
  device/link_types.cc
  device/device_types.cc
  device/device_utils.cc
  device/base_device_model.cc
  device/base_method_port_model.cc
  device/base_port_model.cc
  device/base_link_model.cc
  device/manager.cc
  device/mapping_utils.cc
  device/mapping_info.cc
  device/mapping.cc
  device/logical_device.cc
  device/logical_port.cc
  device/logical_link.cc
  device/base_physical.cc
  device/physical_device.cc
  device/physical_port.cc
  device/physical_link.cc
  device/base_integrated_circuit_model.cc
  device/base_electronics_module_model.cc
  device/base_rackable_model.cc
  device/base_electronics_crate_model.cc
  device/base_electronics_rack_model.cc
  device/base_firmware_model.cc
  device/base_datapoint_model.cc
  device/manager_command_interface.cc
  device/link_end_info.cc
  device/device_link_info.cc
)

list(APPEND VireLibrary_TESTS
  device/testing/test-device-local_role.cxx
  device/testing/test-device-slot.cxx
  device/testing/test-device-single_instance.cxx
  device/testing/test-device-multiple_instance.cxx
  device/testing/test-device-i_instance.cxx
  device/testing/test-device-regular_1d_instance.cxx
  device/testing/test-device-regular_2d_instance.cxx
  device/testing/test-device-base_device_model.cxx
  device/testing/test-device-base_port_model.cxx
  device/testing/test-device-base_method_port_model.cxx
  device/testing/test-device-base_electronics_module_model.cxx
  device/testing/test-device-base_integrated_circuit_model.cxx
  device/testing/test-device-manager.cxx
  device/testing/test-device-manager_2.cxx
  device/testing/test-device-link_end_info.cxx
)
