list(APPEND Vire_RESOURCES
${PROJECT_SOURCE_DIR}/resources/README.rst
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/README.rst
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/urn/db/service.conf
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/urn/db/experiments/db_infos.defs
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/urn/db/devices/db_infos.defs
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/urn/resolvers/service.conf
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/urn/resolvers/devices/map.conf
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/common/devices/1.0/models/network/network.vdm
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/common/devices/1.0/models/electronics/samlong.vdm
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/common/devices/1.0/models/computer/computer.vdm
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/README.rst
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/users/groups.lis
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/users/auth.lis
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/users/users.lis
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/resources/roles.lis
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/resources/manager.conf
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/clients/client-devel1.conf
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/common/common-devel1.conf
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/common/experiment-devel-1.conf
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/common/experiment.conf
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/server/conf.d/devices.conf
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/server/conf.d/pre_system.conf
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/server/conf.d/business.conf
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/server/conf.d/post_system.conf
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/server/main.conf
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/server/server-devel1.conf
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/README.rst
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/TRACKER/TRACKER_CB/ControlBoardModel_Bidon.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/TRACKER/TRACKER_CB/TRACKER_CB_1.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/TRACKER/TRACKER_CB/TRACKER_CB_2.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/TRACKER/TRACKER_CB/ControlBoardModel.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/TRACKER/TRACKER_CB/TRACKER_CB_3.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/TRACKER/TRACKER_CB/createInstanceTRACKER_CB.sh
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/TRACKER/TRACKER_CB/createInstanceTRACKER_CB_Bidon.sh
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/TRACKER/TRACKER_CB_CRATE/TRACKER_ELECTRONICS_CRATE_3.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/TRACKER/TRACKER_CB_CRATE/TRACKER_ELECTRONICS_CRATE_1.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/TRACKER/TRACKER_CB_CRATE/TRACKER_ELECTRONICS_CRATE_2.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/TRACKER/TRACKER_CB_CRATE/createInstanceTRACKER_CB_CRATE.sh
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/TRACKER/TRACKER_CB_CRATE/ELECTRONICS_CRATEModel.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/TRACKER/TRACKER_TRIGGER/createInstanceCALO_Trigger.sh
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/TRACKER/TRACKER_TRIGGER/TriggerBoardModel.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/TRACKER/TRACKER_TRIGGER/TRACKER_TRIGGER_1.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/TRACKER/TRACKER_TRIGGER/createInstanceTRACKER_Trigger.sh
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/TRACKER/TRACKER_TRIGGER/CALO_TRIGGER_1.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/TRACKER/TRACKER_HVPS/TRACKER_HVPS_2.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/TRACKER/TRACKER_HVPS/TRACKER_HVPS_3.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/TRACKER/TRACKER_HVPS/PSType1Model.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/TRACKER/TRACKER_HVPS/createInstanceTRACKER_HVPS.sh
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/TRACKER/TRACKER_HVPS/TRACKER_HVPS_1.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/CMS/DNS/createInstanceDNS.sh
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/CMS/DNS/CMS_DNS_1.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/CMS/DNS/CMS_DNSModel.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/CMS/DNS/CMS_DNS_1.xml_150715
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/DAQ/DAQModel.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/DAQ/createInstanceDAQ.sh
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/DAQ/DAQdevice_1.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/GAS_FACTORY/createInstanceGasFactory.sh
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/GAS_FACTORY/GAS_Factory_1.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/GAS_FACTORY/GAS_FactoryModel.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/COIL/PSType2Model.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/COIL/createInstanceCOIL_PS.sh
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/COIL/COIL_PS_1.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/Plugins/libQuasar_Manager.so
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/Plugins/libSN_CALO_HVPS.so
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/Plugins/libConfig.so
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/Plugins/setup.conf
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/CALORIMETER/CALO_HVPS/CALO_HVPS_3.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/CALORIMETER/CALO_HVPS/CALO_HVPS_2.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/CALORIMETER/CALO_HVPS/createInstanceCALO_HVPS.sh
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/CALORIMETER/CALO_HVPS/CALO_HVPS_Model.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/CALORIMETER/CALO_HVPS/Quasar.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/CALORIMETER/CALO_HVPS/CALO_HVPS_1.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/CALORIMETER/CALO_CB/CALO_CB_1.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/CALORIMETER/CALO_CB/ControlBoardModel_Bidon.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/CALORIMETER/CALO_CB/ControlBoardModel.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/CALORIMETER/CALO_CB/CALO_CB_3.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/CALORIMETER/CALO_CB/createInstanceCALO_CB_bidon.sh
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/CALORIMETER/CALO_CB/createInstanceCALO_CB.sh
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/CALORIMETER/CALO_CB/CALO_CB_2.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/CALORIMETER/CALO_CB_CRATE/CALO_ELECTRONICS_CRATE_3.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/CALORIMETER/CALO_CB_CRATE/CALO_ELECTRONICS_CRATE_2.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/CALORIMETER/CALO_CB_CRATE/CALO_ELECTRONICS_CRATE_1.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/CALORIMETER/CALO_CB_CRATE/createInstanceCALO_CB_CRATE.sh
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/CALORIMETER/CALO_CB_CRATE/ELECTRONICS_CRATEModel.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/CALORIMETER/CALO_TRIGGER/createInstanceCALO_Trigger.sh
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/CALORIMETER/CALO_TRIGGER/TriggerBoardModel.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/CALORIMETER/CALO_TRIGGER/CALO_TRIGGER_1.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/LSM_ENVIRONMENT/LSM_ENVIRONMENT_1.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/LSM_ENVIRONMENT/createInstanceLSM_Environment.sh
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/LSM_ENVIRONMENT/LSM_ENVIRONMENTModel.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/LIGHT_INJECTION/createInstanceLightInjection.sh
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/LIGHT_INJECTION/LIGHT_INJECTIONModel.xmlSav
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/LIGHT_INJECTION/LIGHT_INJECTIONModel.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/LIGHT_INJECTION/LIGHT_INJECTION_1.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/devices_launch.conf
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/SOURCE_CALIBRATION/SOURCE_CALIBRATION_1.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/SOURCE_CALIBRATION/createInstanceSourceCalibration.sh
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.2/SNEMO/SOURCE_CALIBRATION/SOURCE_CALIBModel.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9/SNEMO/TRACKER/TRACKER_CB/TRACKER_CB_1.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9/SNEMO/TRACKER/TRACKER_CB/TRACKER_CB_2.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9/SNEMO/TRACKER/TRACKER_CB/ControlBoardModel.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9/SNEMO/TRACKER/TRACKER_CB/TRACKER_CB_3.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9/SNEMO/TRACKER/TRACKER_CB/createInstanceTRACKER_CB.sh
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9/SNEMO/TRACKER/TRACKER_CB_CRATE/TRACKER_ELECTRONICS_CRATE_1.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9/SNEMO/TRACKER/TRACKER_CB_CRATE/TRACKER_ELECTRONICS_CRATE_2.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9/SNEMO/TRACKER/TRACKER_CB_CRATE/createInstanceTRACKER_CB_CRATE.sh
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9/SNEMO/TRACKER/TRACKER_CB_CRATE/ELECTRONICS_CRATEModel.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9/SNEMO/TRACKER/TRACKER_TRIGGER/TriggerBoardModel.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9/SNEMO/TRACKER/TRACKER_TRIGGER/TRACKER_TRIGGER_1.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9/SNEMO/TRACKER/TRACKER_TRIGGER/createInstanceTRACKER_Trigger.sh
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9/SNEMO/TRACKER/TRACKER_HVPS/PSType1Model.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9/SNEMO/TRACKER/TRACKER_HVPS/createInstanceTRACKER_HVPS.sh
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9/SNEMO/TRACKER/TRACKER_HVPS/TRACKER_HVPS_1.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9/SNEMO/CMS/DNS/createInstanceDNS.sh
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9/SNEMO/CMS/DNS/CMS_DNS_1.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9/SNEMO/CMS/DNS/CMS_DNSModel.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9/SNEMO/DAQ/DAQModel.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9/SNEMO/DAQ/createInstanceDAQ.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9/SNEMO/DAQ/DAQdevice_1.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9/SNEMO/GAS_FACTORY/createInstanceGasFactory.sh
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9/SNEMO/GAS_FACTORY/GAS_Factory_1.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9/SNEMO/GAS_FACTORY/GAS_FactoryModel.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9/SNEMO/COIL/PSType2Model.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9/SNEMO/COIL/createInstanceCOIL_PS.sh
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9/SNEMO/COIL/COIL_PS_1.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9/SNEMO/CALORIMETER/CALO_HVPS/CALO_HVPS_3.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9/SNEMO/CALORIMETER/CALO_HVPS/CALO_HVPS_2.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9/SNEMO/CALORIMETER/CALO_HVPS/PSType1Model.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9/SNEMO/CALORIMETER/CALO_HVPS/createInstanceCALO_HVPS.sh
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9/SNEMO/CALORIMETER/CALO_HVPS/CALO_HVPS_1.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9/SNEMO/CALORIMETER/CALO_CB/CALO_CB_1.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9/SNEMO/CALORIMETER/CALO_CB/ControlBoardModel.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9/SNEMO/CALORIMETER/CALO_CB/CALO_CB_3.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9/SNEMO/CALORIMETER/CALO_CB/createInstanceCALO_CB.sh
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9/SNEMO/CALORIMETER/CALO_CB/CALO_CB_2.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9/SNEMO/CALORIMETER/CALO_CB_CRATE/CALO_ELECTRONICS_CRATE_3.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9/SNEMO/CALORIMETER/CALO_CB_CRATE/CALO_ELECTRONICS_CRATE_2.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9/SNEMO/CALORIMETER/CALO_CB_CRATE/CALO_ELECTRONICS_CRATE_1.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9/SNEMO/CALORIMETER/CALO_CB_CRATE/createInstanceCALO_CB_CRATE.sh
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9/SNEMO/CALORIMETER/CALO_CB_CRATE/ELECTRONICS_CRATEModel.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9/SNEMO/CALORIMETER/CALO_TRIGGER/createInstanceCALO_Trigger.sh
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9/SNEMO/CALORIMETER/CALO_TRIGGER/TriggerBoardModel.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9/SNEMO/CALORIMETER/CALO_TRIGGER/CALO_TRIGGER_1.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9/SNEMO/LSM_ENVIRONMENT/LSM_ENVIRONMENT_1.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9/SNEMO/LSM_ENVIRONMENT/createInstanceLSM_Environment.sh
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9/SNEMO/LSM_ENVIRONMENT/LSM_ENVIRONMENTModel.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9/SNEMO/LIGHT_INJECTION/createInstanceLightInjection.sh
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9/SNEMO/LIGHT_INJECTION/LIGHT_INJECTIONModel.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9/SNEMO/LIGHT_INJECTION/LIGHT_INJECTION_1.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9/SNEMO/SOURCE_CALIBRATION/SOURCE_CALIBRATION_1.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9/SNEMO/SOURCE_CALIBRATION/createInstanceSourceCalibration.sh
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9/SNEMO/SOURCE_CALIBRATION/SOURCE_CALIBModel.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/doc/SNEMO_deviceModels&InstancesVert.png
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/TRACKER/TRACKER_CB/ControlBoardModel_Bidon.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/TRACKER/TRACKER_CB/TRACKER_CB_1.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/TRACKER/TRACKER_CB/TRACKER_CB_2.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/TRACKER/TRACKER_CB/ControlBoardModel.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/TRACKER/TRACKER_CB/TRACKER_CB_3.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/TRACKER/TRACKER_CB/createInstanceTRACKER_CB.sh
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/TRACKER/TRACKER_CB/createInstanceTRACKER_CB_Bidon.sh
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/TRACKER/TRACKER_CB_CRATE/TRACKER_ELECTRONICS_CRATE_3.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/TRACKER/TRACKER_CB_CRATE/TRACKER_ELECTRONICS_CRATE_1.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/TRACKER/TRACKER_CB_CRATE/TRACKER_ELECTRONICS_CRATE_2.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/TRACKER/TRACKER_CB_CRATE/createInstanceTRACKER_CB_CRATE.sh
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/TRACKER/TRACKER_CB_CRATE/ELECTRONICS_CRATEModel.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/TRACKER/TRACKER_TRIGGER/createInstanceCALO_Trigger.sh
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/TRACKER/TRACKER_TRIGGER/TriggerBoardModel.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/TRACKER/TRACKER_TRIGGER/TRACKER_TRIGGER_1.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/TRACKER/TRACKER_TRIGGER/createInstanceTRACKER_Trigger.sh
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/TRACKER/TRACKER_TRIGGER/CALO_TRIGGER_1.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/TRACKER/TRACKER_HVPS/TRACKER_HVPS_2.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/TRACKER/TRACKER_HVPS/TRACKER_HVPS_3.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/TRACKER/TRACKER_HVPS/PSType1Model.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/TRACKER/TRACKER_HVPS/createInstanceTRACKER_HVPS.sh
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/TRACKER/TRACKER_HVPS/TRACKER_HVPS_1.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/CMS/DNS/createInstanceDNS.sh
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/CMS/DNS/CMS_DNS_1.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/CMS/DNS/CMS_DNSModel.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/CMS/DNS/CMS_DNS_1.xml_150715
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/DAQ/DAQModel.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/DAQ/createInstanceDAQ.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/DAQ/createInstanceDAQ.sh
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/DAQ/DAQdevice_1.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/GAS_FACTORY/createInstanceGasFactory.sh
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/GAS_FACTORY/GAS_Factory_1.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/GAS_FACTORY/GAS_FactoryModel.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/COIL/PSType2Model.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/COIL/createInstanceCOIL_PS.sh
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/COIL/COIL_PS_1.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/Plugins/libQuasar_Manager.so
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/Plugins/libSN_CALO_HVPS.so
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/Plugins/libConfig.so
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/Plugins/setup.conf
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/CALORIMETER/CALO_HVPS/CALO_HVPS_3.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/CALORIMETER/CALO_HVPS/CALO_HVPS_2.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/CALORIMETER/CALO_HVPS/createInstanceCALO_HVPS.sh
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/CALORIMETER/CALO_HVPS/CALO_HVPS_Model.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/CALORIMETER/CALO_HVPS/Quasar.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/CALORIMETER/CALO_HVPS/CALO_HVPS_1.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/CALORIMETER/CALO_CB/CALO_CB_1.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/CALORIMETER/CALO_CB/ControlBoardModel_Bidon.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/CALORIMETER/CALO_CB/ControlBoardModel.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/CALORIMETER/CALO_CB/CALO_CB_3.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/CALORIMETER/CALO_CB/createInstanceCALO_CB_bidon.sh
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/CALORIMETER/CALO_CB/createInstanceCALO_CB.sh
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/CALORIMETER/CALO_CB/CALO_CB_2.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/CALORIMETER/CALO_CB_CRATE/CALO_ELECTRONICS_CRATE_3.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/CALORIMETER/CALO_CB_CRATE/CALO_ELECTRONICS_CRATE_2.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/CALORIMETER/CALO_CB_CRATE/CALO_ELECTRONICS_CRATE_1.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/CALORIMETER/CALO_CB_CRATE/createInstanceCALO_CB_CRATE.sh
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/CALORIMETER/CALO_CB_CRATE/ELECTRONICS_CRATEModel.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/CALORIMETER/CALO_TRIGGER/createInstanceCALO_Trigger.sh
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/CALORIMETER/CALO_TRIGGER/TriggerBoardModel.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/CALORIMETER/CALO_TRIGGER/CALO_TRIGGER_1.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/LSM_ENVIRONMENT/LSM_ENVIRONMENT_1.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/LSM_ENVIRONMENT/createInstanceLSM_Environment.sh
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/LSM_ENVIRONMENT/LSM_ENVIRONMENTModel.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/LIGHT_INJECTION/createInstanceLightInjection.sh
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/LIGHT_INJECTION/LIGHT_INJECTIONModel.xmlSav
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/LIGHT_INJECTION/LIGHT_INJECTIONModel.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/LIGHT_INJECTION/LIGHT_INJECTION_1.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/devices_launch.conf
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/SOURCE_CALIBRATION/SOURCE_CALIBRATION_1.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/SOURCE_CALIBRATION/createInstanceSourceCalibration.sh
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/cms/mos_xml/0.9.1/SNEMO/SOURCE_CALIBRATION/SOURCE_CALIBModel.xml
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/devices/0.1/README.rst
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/devices/0.1/models/demonstrator/detector/source_frame/source_frame.vdm
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/devices/0.1/models/demonstrator/detector/tracker/tracker.vdm
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/devices/0.1/models/demonstrator/detector/tracker/drift_cell.vdm
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/devices/0.1/models/demonstrator/detector/models.lis
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/devices/0.1/models/demonstrator/detector/calorimeter/calorimeter.vdm
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/devices/0.1/models/demonstrator/detector/tent/tent.vdm
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/devices/0.1/models/demonstrator/detector/detector.vdm
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/devices/0.1/models/demonstrator/detector/OM/om.vdm
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/devices/0.1/models/demonstrator/detector/coil/coil.vdm
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/devices/0.1/models/demonstrator/detector/shielding/shielding.vdm
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/devices/0.1/models/demonstrator/electronics/rack_1.vdm
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/devices/0.1/models/demonstrator/electronics/tracker_feb.vdm
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/devices/0.1/models/demonstrator/electronics/rack_2.vdm
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/devices/0.1/models/demonstrator/electronics/rack_4.vdm
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/devices/0.1/models/demonstrator/electronics/calo_feb.vdm
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/devices/0.1/models/demonstrator/electronics/calo_control_board.vdm
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/devices/0.1/models/demonstrator/electronics/electronics.vdm
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/devices/0.1/models/demonstrator/electronics/miscellaneous.vdm
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/devices/0.1/models/demonstrator/electronics/tracker_hv_crate.vdm
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/devices/0.1/models/demonstrator/electronics/models.lis
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/devices/0.1/models/demonstrator/electronics/tracker_crates.vdm
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/devices/0.1/models/demonstrator/electronics/rack_0.vdm
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/devices/0.1/models/demonstrator/electronics/trigger_board.vdm
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/devices/0.1/models/demonstrator/electronics/ads_crate.vdm
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/devices/0.1/models/demonstrator/electronics/tracker_control_board.vdm
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/devices/0.1/models/demonstrator/electronics/ads_crates.vdm
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/devices/0.1/models/demonstrator/electronics/calo_hv_crate.vdm
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/devices/0.1/models/demonstrator/electronics/calo_crates.vdm
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/devices/0.1/models/demonstrator/electronics/rack_3.vdm
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/devices/0.1/models/demonstrator/electronics/rack_5.vdm
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/devices/0.1/models/demonstrator/demonstrator.vdm
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/devices/0.1/models/demonstrator/cms/cms.vdm
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/devices/0.1/models/demonstrator/cms/models.lis
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/devices/0.1/models/setup.vdm
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/devices/0.1/mapping/README.rst
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/devices/0.1/mapping/setup.vdc
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/devices/0.1/mapping/demonstrator/CMS/CMS.vdc
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/devices/0.1/mapping/demonstrator/detector/detector.vdc
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/devices/0.1/mapping/demonstrator/detector/calorimeter.vmr
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/devices/0.1/mapping/demonstrator/detector/coil.vdc
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/devices/0.1/mapping/demonstrator/detector/shielding.vdc
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/devices/0.1/mapping/demonstrator/detector/tent.vdc
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/devices/0.1/mapping/demonstrator/detector/source_frame.vdc
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/devices/0.1/mapping/demonstrator/detector/tracker.vdc
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/devices/0.1/mapping/demonstrator/detector/calorimeter.vdc
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/devices/0.1/mapping/demonstrator/detector/detector.vmr
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/devices/0.1/mapping/demonstrator/electronics/electronics.vmr
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/devices/0.1/mapping/demonstrator/electronics/electronics.vdc
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/devices/0.1/mapping/demonstrator/demonstrator.vmr
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/devices/0.1/mapping/setup.vmr
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/devices/0.1/devices.txt
${PROJECT_SOURCE_DIR}/resources/sandbox/snemo/config/snemo/demonstrator/devices/0.1/manager.conf
)
